### ISSUE TITLE
3. How properties should be stored inside the StructureData Node

### ISSUE THREAD

**Issue by mikibonacci** [aiidateam/aiida-atomistic#3]
###  The `properties` namespace

Properties may be stored inside an attribute called `properties`. For example in case of the `pbc` property, it should be stored as `StructureData.properties.pbc`: this is the class `Pbc` and its actual value (which is a list of booleans) can be accessed via `StructureData.properties.pbc.value`. 

- everything in the `properties` attribute can be subject to a consistency check, to understand if there is something unknown. and then raise an error (the same check can be done via the structure.get_valid_properties() and structure.get_defined_properties() methods).
- The question also becomes: what is a property? Are the `pbc` a property? What about the mass of each site?

### Physical storage of a property: database of repository?

The advantage of database (storing properties as attribute of StructureData node) is that it is possible to *query* and search. The repository, instead, is not subject to any query. 
However, for example in case of Hubbard parameters (see HubbardStructureData), these are stored in the repository as JSON files, using *pydantic* functionalities.

Sometimes, we want to be queryable only some part of the properties. This means that we can design a property class to determine which of its parameters/values should be stored and where; we add a level of flexibility for the storage location.  This flexibility however should be only in the implementation of the property, i.e. we cannot decide the storage location on-the-fly when creating  a StructureData instance.
- The getter and setter methods (of the current implementation) should be adjusted to be general and support both db- and repo- based type of properties. Or we should define two different methods, one for db and one for repository
 
#### DB-like properties
Stored in self.base.attributes._property_attributes dictionary. --> should change to self.base.attributes.property

#### Repository-like properties
Stored in the repository and accessed via *pydantic* BaseModel  functionalities.

```[tasklist]
### Tasks
- [x] Fix the recovery of the `properties` attribute once the StructureData node is loaded again
- [ ] Add possibility to store a property in db or in repository (the decision is property-specific, for now we can store everything in the db)
- [ ] create a documentation on simple query of the properties
```

**Comment by mikibonacci** [comment]
Up to now, in the current implementation of the atomistic StructureData (main branch), all the properties are under the `properties` attribute directly:

```python
unit_cell = [[3.5, 0.0, 0.0], [0.0, 3.5, 0.0], [0.0, 0.0, 3.5]]
atomic_positions = [[0.0, 0.0, 0.0],[1.5, 1.5, 1.5]]
symbols = ["Li"]*2
mass = [6.941,6.941]
charge = [1,0]

properties = {
    "cell":{"value":unit_cell},
    "pbc":{"value":[True,True,True]},
    "positions":{"value":atomic_positions,},
    "symbols":{"value":symbols},
    "mass":{"value":mass,},
    "charge":{"value":charge}
    }

structure = StructureData(
        properties=properties
        )
```
we can access the properties in this way:
```python
structure.properties.cell 
structure.properties.symbols
...
```
Each properties has an attribute called `domain`, which can be `global` (pbc, cell) `intra-site` (mass, charge,positions,symbols) or `inter-site` (Hubbard V, not yet implemented). 

Another possibility is to have this domains (maybe with different names) as attributes of the `properties`, and then under these three have the related properties (structure.properties.global.cell ... ):
```python
unit_cell = [[3.5, 0.0, 0.0], [0.0, 3.5, 0.0], [0.0, 0.0, 3.5]]
atomic_positions = [[0.0, 0.0, 0.0],[1.5, 1.5, 1.5]]
symbols = ["Li"]*2
mass = [6.941,6.941]
charge = [1,0]

properties = {
    "global":{
         "cell":unit_cell,
        "pbc":[True,True,True],
     },
    "sites":{
        "positions":atomic_positions,
        "symbols":symbols,
        "mass":mass,
        "charge":charge,
     }
}

structure = StructureData(
        properties=properties
        )
```
we can access the properties in this way:
```python
structure.properties.global.cell 
structure.properties.sites.symbols
...
```

I have the feeling that this way of providing properties is cleaner and that can also make easier the transition of the plugins to the atomistic Data. However I am not sure it is a good alternative. 
Each sub-property will be then an attribute of the GlobalProperty or SitesProperty classes. Instead of a list of `supported_properties`, we can provide a dictionary:

```python
In [1]: structure.properties.get_supported_properties()
Out [1]: {
                  "global":["pbc","cell"],
                   ...
               }
```

Comments @sphuber , @giovannipizzi , @mbercx ?

**Comment by sphuber** [comment]
What is the advantage of classifying the properties according to their "domain"? Is having this knowledge encoded in the property itself necessary? Surely, the developer will know that the `cell` is "global" and the `mass` is a site-specific property.

**Comment by mikibonacci** [comment]
I agree that the developer will know the domain of a given property. 
And classifying with an additional attribute layer may complicate things. 

Thanks  @sphuber .

**Comment by superstar54** [comment]
I think using `domain` is a good design in the long term. The property could be site-specific, or kind-specific, or belong to the structure. By specific the property domain, the code can treat the property differently. For example, when I create a supercell, the code can automatically determine which properties need to be replicated or preserved, based on their domain. This makes the process more straightforward and less error-prone.

Regarding the `mass` property, one could also define it as a kind-specific property. Maybe some code QE would like a property to be kind-specific, while other codes require the property to be site-specific. Relying on developers to inherently know or remember the domain of each property increases the risk of mistakes.

**Comment by mikibonacci** [comment]
I agree on the domain, in the end it is a cost-zero feature which may turn out to be useful. 
About the case of the `mass` property, I would prefer to leave it as site-based, as all the other domain==intra-site properties. One reason is that in this way we still have a code-agnostic definition of the masses, and the second one is that the `kind` property will be defined alongside the other (see https://github.com/aiidateam/aiida-atomistic/issues/4). So in a way we are still using the kinds but at the same time we have a site-based definition.

**Comment by sphuber** [comment]
> For example, when I create a supercell, the code can automatically determine which properties need to be replicated or preserved, based on their domain. 

I think this is a good example. Note that I didn't say that adding this information is not a good idea, I was just asking for use-cases.

I am just wondering about the interface and the requirements/guarantees. Does the internal implementation do anything with the domain information of the property? Or is it solely up to the consumer to use that information?

Regarding the API, I think making the domain available on the property makes sense. Not so sure about making the domain a subnamespace through which to access the property, i.e. `node.properties.global.cell` is not ideal I would say.

**Comment by mikibonacci** [comment]
For now the implementation just stores the domain information, without using it. The use case of the supercell can be also implemented in the StructureData as a method to return easily a new StructureData node containing the supercell.

About exposing the domain property as attribute in the nesting `node.properties.global.cell`, I agree that it is not ideal. 
Right now I am also concerned about the "value" attribute which allows to access the value of a property:

```python
In [1]: node.properties.pbc.value
Out[1]: [True,True,True]
```

as you can also see in https://github.com/aiidateam/aiida-atomistic/issues/9.
because it seems a bit counter-intuitive: a user expects to access the pbc value just accessing `node.properties.pbc`. The "value" additional layer was provided in case we need also additional parameters for each properties, for example a specific kind detection threshold.
However, we can think to pass kind threshold and other parameters to the constructor. 
This will simplify the construction of the properties input dictionary and probably simplify also its modifications:
